### ISSUE TITLE
Write a function instead of using a dict for powers

### ISSUE THREAD

**Issue by attilavs2** [TinyTakinTeller/GodotProjectZero#33]
https://github.com/TinyTakinTeller/GodotProjectZero/blob/4dce1fdfa7cd3fa8ba2cfb704058e974aea5b8e7/global/utils/pow_utils.gd#L3
???
???
Make a function for that pls

**Comment by TinyTakinTeller** [comment]
Thanks for reminding me about this.

Why did I decide to use stored values instead of a function?

In old systems where exponentiation is used a lot, it is more practical to have pre-computed stored values instead of a function. I don't know why, but that example fell on my mind in the moment when I was thinking "I need an integer power function".

Perhaps simplest would've been to just round up the built-in float power function.

But it really does not matter for the current game if we use a pre-computed dictionary or [a general function](https://en.wikipedia.org/wiki/Exponentiation_by_squaring) or if we simply round up the built-in function. Every of these three approaches seems fine to me.

There are much more important things on the TODO list at the moment.

But if you want, you can make a pull request to add a general integer power function to the PowUtils node.

In the mean time, I'm closing this issue.

**Comment by TinyTakinTeller** [comment]
It appears there is an edge case where exponent 19 is used (larger than max allowed in current dictionary) when the amount of resources is being grinder very fast. (see report in wild: https://itch.io/t/4083026/locked-out )

Re-opening this issue for this reason.

**Comment by TinyTakinTeller** [comment]
Fixed by https://github.com/TinyTakinTeller/GodotProjectZero/commit/9c4e7ab4c9fe9523fb36db8afaa18a8d61c6bfc0

**Comment by attilavs2** [comment]
Thanks for taking in my comment even if it was because of another reason
